CREATE TABLE "PROFILES" (
  "ID"          VARCHAR PRIMARY KEY,
  "FIRST_NAME"  VARCHAR NOT NULL,
  "LAST_NAME"   VARCHAR NOT NULL,
  "TIPO_IPF"    VARCHAR(1) NOT NULL,
  "NUM_IPF"     VARCHAR(10) NOT NULL,
  "DUP_IPF"     VARCHAR(2) NOT NULL,
  "DES_IPF"     VARCHAR(2) NOT NULL
);
